### ISSUE TITLE
Saving new has_many will not retain original sort order.

### ISSUE THREAD

**Issue by patricknelson** [bummzack/sortablefile#30]
I'm not sure about new `many_many` relationships (since in my system all of them are pages which are already saved), but when setting a new parent object with a `has_many` relation to sorted files, it looks like it wasn't saving the sort order at all. I'll submit a separate pull request for this for initial review (I'm not sure it'll be ready for use just yet, since I don't have any `many_many` relations to test).

**Comment by bummzack** [comment]
Thanks a lot for your PRs. Everything should now be merged into master, 1.1.

**Comment by patricknelson** [comment]
Ok awesome. Were you able to test the `many_many` relation when saving a new parent object (pointing to the `many_many` relation of files)? That's one thing I didn't have time to setup and test on my end.

**Comment by bummzack** [comment]
Yes, that works, thanks.
