### ISSUE TITLE
Change strict check on has_many() away from === null

### ISSUE THREAD

**Issue by patricknelson** [bummzack/sortablefile#37]
There is currently a bug in SS core `DataObject` method `->has_many()` which doesn't properly/consistently return `null` as expected, instead it is returning `false`, see here: https://github.com/silverstripe/silverstripe-framework/pull/4130

While we wait for that fix, for backward compatibility and to address this issue now in this module, I'll be loosening the strictness of this check for the time being. PR to come shortly.

**Comment by patricknelson** [comment]
Specifically - this bug in SS affects this line in this module: https://github.com/bummzack/sortablefile/commit/255eb4f2d0f84acc3adde9492b406cbabb7e2e4d#diff-4e2b5668e9d16922b711d26d14ef007bR95

**Comment by bummzack** [comment]
Thanks for the temp. fix.
