### ISSUE TITLE
Having trouble using this on the front end

### ISSUE THREAD

**Issue by phil-quinn** [bummzack/sortablefile#40]
First off, thank you so much for building this. We use it all the time.

We are now working on a project where we would like to use SortableUploadField in the front end of a site in addition to within the CMS. And we keep running into an error when we try to actually sort: 
Failed to load resource: the server responded with a status of 403 (Forbidden)

All the other actions, like edit, delete, etc. seem to work fine.

I _think_ I've tracked it down to a problem in the "sort" function inside the "SortableUploadField_ItemHandler" class. 

This line:
$record = $this->parent->getRecord();

This seems to not return a record unless you are in the CMS. And thus fails the next line:
if ($record && $record->hasMethod($relationName)) { ... }

Do you know if anyone has figured out a way around this to use this Form Field in the front end of a site?

Thanks!

**Comment by bummzack** [comment]
Hm that's strange. I have used the SortableUploadField in a frontend form in the past. Do you initialize the field with an existing record? Or how does your use-case look like?

**Comment by phil-quinn** [comment]
I’ve tried it a number of different ways.

The thing I might be doing that’s odd is that I’m doing this on a CMS-less site. So I have this attached to a DataObject and/or Controller but not a SiteTree object.

Could that cause any problems?

-Phil

> On May 23, 2015, at 12:01 AM, bummzack <notifications@github.com> wrote:
> 
> Hm that's strange. I have used the SortableUploadField in a frontend form in the past. Do you initialize the field with an existing record? Or how does your use-case look like?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Phil Quinn – President, Quinn Interactive, Inc.
912 Cole Street #129, San Francisco, CA 94117
415/296-9000 – https://quinn.com

Know anyone who needs a better website? We'd love the referral!

**Comment by bummzack** [comment]
I just tried the SortableUploadField in a setup without CMS and it works. The only issue I had were some incorrectly ordered requirement imports, which is now fixed with the latest commit.

Here's my complete setup:
https://gist.github.com/bummzack/5d9507c88398508b87d2

There's a controller and a route to it, a DataRecord that the form gets written into and a template to render the controller.

Maybe you need to create a simplified version of your setup that replicates the problem?

**Comment by phil-quinn** [comment]
Thanks!!! I really appreciate you taking the time to look at this.

In your example, you only are making a new DataRecord. I have forked/tweaked the gist to deal with an existing record (after initially creating a new one). It always uses the first one created. Also, for testing, I am working on a site with the Simple Theme.

https://gist.github.com/phil-quinn/0a4f21f0e7a303166979

I noticed that the sort doesn’t happen on save. The GUI allows for sorting, but on save the orders of things do not change. 

The only reason that confuses me is that in the form I have on my other project, the SortableUploadField seems to be trying to do a live sort update via ajax whenever I sort anything. 

So here are my next questions:

1) On my other project, I am bringing in the fields from getFrontEndFields() on my DataObject. Could that be complicating things? And could that be why I am getting the Ajax attempt at live data-updating sorting? Is that only supposed to be happening in the CMS?

2) If on the front end, I do NOT want to have Ajax live data-updating sorting, do I need to re-sort things based on the $data I get back in the form in my form action function? 

Thanks again for all your help. It is very generous of you!

-Phil


> On May 27, 2015, at 5:26 AM, bummzack <notifications@github.com> wrote:
> 
> I just tried the SortableUploadField in a setup without CMS and it works. The only issue I had were some incorrectly ordered requirement imports, which is now fixed with the latest commit.
> 
> Here's my complete setup:
> https://gist.github.com/bummzack/5d9507c88398508b87d2
> 
> There's a controller and a route to it, a DataRecord that the form gets written into and a template to render the controller.
> 
> Maybe you need to create a simplified version of your setup that replicates the problem?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Phil Quinn – President, Quinn Interactive, Inc.
912 Cole Street #129, San Francisco, CA 94117
415/296-9000 – https://quinn.com

Need a better website? Contact us to find out how we can help you create a more effective, flexible, and easier to manage website!

**Comment by bummzack** [comment]
How the sort-order is being updated depends on the state of the record. If there's an existing record/relation, the sorting will update via ajax request. When there's no existing record, sorting won't trigger any requests and save upon submitting the form. So what you're seeing is normal behavior.

I think what you're encountering is simply a permission issue. Sorting checks for edit permissions on the image... and I guess that causes the 403 error on a frontend-form.

I'll add a configuration method to allow frontend sorting.

**Comment by bummzack** [comment]
I added a config flag to the `SortableUploadField` to skip permission checks when sorting. It's in the latest commit.

I also updated the GIST accordingly: https://gist.github.com/bummzack/d4bbe6d38a1879ae028b

Use: `$uploadField->setEnablePermissionCheck(false);` to disable permission checks and prevent frontend form errors.

I hope that solves your issue.
