### ISSUE TITLE
3.3 Compatibility?

### ISSUE THREAD

**Issue by prij** [bummzack/sortablefile#46]
Is this compatible with 3.3?

Have installed + set it up but cannot get the drag and drop file sorting to work. The field renders, but looks like an UploadField without the sorting capability.

I have previously used it successfully with 3.1.

I am using it with a many_many relation. 

Sortorder is defined:
```
private static $many_many_extraFields = array(
        'Files' => array(
        	'SortOrder' => 'Int'
        )
    );
```

File extension has been created + applied:
```
File:
  extensions:
    - DocumentFileExtension
    - Sortable
```

**Comment by bummzack** [comment]
It should work with 3.3, yes. With `many_many` relations, you shouldn't add the `Sortable` extension though.

**Comment by prij** [comment]
I can confirm that it does work with 3.3 - I've just installed it with a fresh install of Silverstripe and it works fine.

I'm trying to use it with CWP (with the latest version of SS), but it's not working there. It may be conflicting with another module that's included in the base recipe. Will investigate further.

**Comment by prij** [comment]
Ok so it appears as though an injection manager definition in the cwp config for UploadField is taking precedence over any other type of UploadField I try to define (so the SortableUploadField is never being rendered).

This is not a SortableUploadField issue, and can be closed :)
