### ISSUE TITLE
Changing order of newly uploaded images does not get saved in the CMS

### ISSUE THREAD

**Issue by Taitava** [bummzack/sortablefile#47]
Well, the topic pretty much tells it all. I have a custom DataObject class and when I manage an instance of it in the ModelAdmin, I upload some images so they appear on the list and then drag them to a different order without saving in the middle. When I finally save, the images appear in an incorrect order after saving. If I then reorder them and save, it works, so I think it is related to the fact that the Image objects are new, perhaps unsaved (I don't know at which point SilverStripe saves them to the database).

Thank you for your support! Please let me know if you need more details.

**Comment by bummzack** [comment]
What version of SilverStripe are you using? Also, is it a `has_many` or `many_many` relation? Or both?

**Comment by Taitava** [comment]
Sorry for the delay. Now I have the same bug in another project too, but I'll first answer to your questions from the first project's point of view:

The SilverStripe version is 3.1.16 and it's using $has_many:
```
private static $has_many = array(
	'Images'			=> 'DogImage',
);
```

Here is the DogImage class:
```
class DogImage extends Image
{
	
	static $has_one = array(
        'Dog' => 'Dog',
    );
    
}
```


And the second project is using SilverStripe 3.4.0 and it's using $many_many (when I set it up, I didn't remember how I did it the last time so that's why I've done it differently):
```
private static $many_many = array(
	'Images'	=> 'CarouselImage',
);
```

CarouselImage class:
```
class CarouselImage extends Image
{
	private static $belongs_many_many = array(
		'Pages' => 'CarouselPage',
	);
	
	private static $default_sort = 'SortOrder';
}
```

With the second project the issue is that the order never gets saved, and the wrong order shows up both in backend and frontend.

**Comment by bummzack** [comment]
Generally, you can avoid a lot of problems if you *don't* use subclasses of `Image`. Add your custom fields and code via an Extension to Image. An example where you'll break a system with subclasses of Image:

 1. Upload an Image via AssetAdmin (the image will have the class `Image`).
 2. Select said image via UploadField (using "From files")
 3. You now have an `Image` in there, but it should be a `DogImage`… ouch?

But I think the above isn't what is causing your issues.
In case of a `has_many` relation, you should add the `Sortable` extension to your custom image class… did you do that?

And in case of a `many_many` relation, you also need:
```
private static $many_many_extraFields = array(
    'Images' => array('SortOrder' => 'Int')
);
```
Did you do that, but forgot it to post in your code above?

**Comment by Taitava** [comment]
Actually just after I posted, I noticed that the extraFields part was missing. But adding it just made the problem worse - now SilverStripe throws an error message sayin "There has been an error" when I save the page :D. But I guess I need to hunt that one down myself, as it may be a completely different topic :). So maybe the second project's issue is now solved.

Both of the projects have the correct extension defined in the config files.

Thanks for the advice about not using subclasses of Image! It's a good point and I have to keep that in mind in the future.

So at least the first project's problem is still a mystery to me, but I guess that if it's hard to solve, I just leave it as is.

**Comment by bummzack** [comment]
Don't add the `Sortable` extension to image in case you use `many_many`! Also don't forget to do `dev/build`, otherwise the DB field will be missing.

**Comment by Taitava** [comment]
Thanks, that solved the problem with the second project! :) I removed the extension from the config and now it doesn't throw an error any more when saving :). And yes, I didn't forget /dev/build :).

**Comment by Taitava** [comment]
Conclusion about the original problem: with a `has_many` relation, the relation between a `DogImage` and it's master object (well, `Dog` :) ) is not saved at the time of _upload_. The relation gets saved after the user hit's the save button. (Well, this was not actually any news to me, but let's continue).

This creates a tiny issue: When a new image is uploaded, and the user drags _old_ images around _before_ hitting the save button in between, the drag&drop sort method - run on the server via ajax - is not aware of the newly uploaded image(s) and therefore is not able to take that into account. I think that in this situation the new image will still go to the end of the queue at the time when the user hits the save button, regardless of if the user has dragged _other_ (old) images past the newly uploaded one.

One way to fix this: save the relation by using `DogImage::onBeforeWrite()` , check if the image is new and set `$this->DogID = *get value from the request url*`.

Perhaps there would be an other way to find out how to fix this in the `sortablefile` module, so that the above fix would not be necessary? But if not, or if it would be hard to do, then no need to use too much time :).

For me I think I could consider this issue resolved now. I will close it now, as I have found my own way to settle this, but if you @bummzack (or anyone else) happen to find out something that could improve this a little bit, then this issue can be reopened if needed. Thanks! :)

(I hope this comment is not too messy. Need to go to sleep now :D.)
