### ISSUE TITLE
Silverstripe 3.4.0 doesn't record order

### ISSUE THREAD

**Issue by Digitweaks** [bummzack/sortablefile#48]
Hi, i'm working on SS 3.4.0 and with a many_many relationship, all looks perfect but the SortableGridField doesn't record the new Order when we save the object ( i made a GalleryObject instead of a GalleryPage so i can have multiple galleries on a page )

**Comment by bummzack** [comment]
So you have a DataObject that has `many_many` Images? Did you add the `SortOrder` via `many_many_extraFields`?

You'll also have to apply the sorting when accessing the relation. Eg.

    <% loop $Images.Sort('SortOrder') %>
      
    <% end_loop %>

**Comment by Digitweaks** [comment]
Yes i did. Actually showing the pictures works perfectly, the issue comes when i drag and change the order in the gridfield, in the backend, it simply comes back to it's normal position after pressing "save & publish"

**Comment by Digitweaks** [comment]
i can maybe show you the code

<?php

class GalleryImageExtension extends DataExtension {
        private static $belongs_many_many = array('Galleries' => 'GalleryObject');
}

//----- ADD EXTENSION TO IMAGE IN config.yml ---------

class GalleryObject extends DataObject {
    
	private static $db = array(
        'Title'=>'Text',
        'URLSegment'=>'Varchar',
        'FolderName'=>'Varchar',
        'Description'=>'HTMLText',
        'SEODescription'=>'Text',
        'Date'=>'Date',
        'Order'=>'Int',
        'IsActive'=>'Boolean(1)',
        'RelativeActive'=>'Boolean(1)',
        'FeaturedOnHomepage'=>'Boolean',
	);
    
    public static $default_sort='Order';
    
	private static $has_one = array(
        'Thumb'=>'Image',
        'GalleryPage'=>'GalleryPage'
	);
    
    private static $many_many = array(
        'BlogTags' => 'BlogTag',
        'GalleryImages' => 'Image',
    );
    
    private static $belongs_many_many = array(
        'BlogPosts' => 'BlogPostObject',
        'Events' => 'EventObject'
    );
    
    static $summary_fields = array(
        'Title' => 'Title',
        'MyThumb'=>'Thumb',
        'Type'=>'Type',
        'Order'=>'Order'
    );
    
    public function populateDefaults(){
        parent::populateDefaults();
        $this->Date = date('Y-m-d');
    }
    
    public function Title(){
        return $this->Title;
    }

    public function MyThumb(){ 
	   return $this->Thumb()->SetWidth(160);
    }
    
    function getOGImage() {
        return $this->Thumb();
    }

    function getOGDescription(){
        return $this->SEODescription;
    }
    
    public function MetaTags($includeTitle = true) {
        $tags = "";
        // Insert non-OG metatags here as you normally would
        $this->extend('MetaTags', $tags);
        return $tags;
    }
    
    function SortedPictures() {
    return $this->Pictures()->Sort('Order');
    }
    
    function canView($member = null) {
        return true;
    }
    
    function AbsoluteLink() {
        return Director::absoluteURL($this->Link());
    }
    
    public function Link(){
            return $this->GalleryPage()->Link('show/'.$this->ID."/".$this->URLSegment);
    }
    
    public function LinkGallery(){
            return $baseURL.'galleries/show/'.$this->ID.'/'.$this->URLSegment;
    }
    
    public function LinkingMode(){
        return Controller::curr()->getRequest()->param('ID') == $this->ID ? 'current' : 'link';
    }

    function onBeforeWrite () {
		parent::onBeforeWrite ();
		if($this->Title)
			$this->URLSegment = SiteTree::generateURLSegment($this->Title);
	}
    
    public function getCMSFields(){
        $fields = FieldList::create(TabSet::create('Root'));
        $fields->addFieldsToTab('Root.Main', array(
            TextField::create('Title'),
            TextField::create('URLSegment'),
            TextField::create('FolderName'),
            HTMLEditorField::create('Description'),
            TextareaField::create('SEODescription'),
            DateField::create('Date')->setConfig('dateformat', 'dd-MM-yyyy')->setConfig('showcalendar', true),
            NumericField::create('Order'),
            CheckboxField::create('RelativeActive','Show Relative Content'),
            TagField::create('BlogTags','Blog Tags',BlogTag::get(),$this->BlogTags())->setShouldLazyLoad(true)->setCanCreate(true)     // new tag DataObjects can be created
        ));
        $fields->addFieldToTab('Root.Main',$upload = new UploadField('Thumb'));
        $upload->SetFolderName('GalleryThumbs');
        
        $fields->addFieldToTab(
                                'Root.Upload',
                                $uploadField = new UploadField($name = 'GalleryImages', $title = 'Upload one or more images')
                              );
        $uploadField->setFolderName($this->URLSegment);
        $uploadField->setAllowedMaxFileNumber(32);
        
        $this->extend('updateCMSFields', $fields);
        return $fields;
    } 
    
}

**Comment by Digitweaks** [comment]
In the lasts lines, there's 

`$fields->addFieldToTab(
                            'Root.Upload',
                            $uploadField = new UploadField($name = 'GalleryImages', $title = 'Upload one or more images')
                          );
`

if i replace "GalleryImages" by "SortedImages", it works but in this version i didn't put the extrafield cause i came backwards, so don't mind the lack of many_many_extrafields

**Comment by Digitweaks** [comment]
So, with GalleryImages, it goes back to its original position, with SortedImages, it records but i have to reload the page cause of course, it creates a bug

**Comment by Digitweaks** [comment]
Sorry, this is the proper version i tried to use `<?php

class GalleryImageExtension extends DataExtension {
        private static $belongs_many_many = array('Galleries' => 'GalleryObject');
        private static $db = array('SortOrder' => 'Int');
}

//----- ADD EXTENSION TO IMAGE IN config.yml ---------

class GalleryObject extends DataObject {
    
	private static $db = array(
        'Title'=>'Text',
        'URLSegment'=>'Varchar',
        'FolderName'=>'Varchar',
        'Description'=>'HTMLText',
        'SEODescription'=>'Text',
        'Date'=>'Date',
        'Order'=>'Int',
        'IsActive'=>'Boolean(1)',
        'RelativeActive'=>'Boolean(1)',
        'FeaturedOnHomepage'=>'Boolean',
	);
    
    public static $default_sort='Order';
    
	private static $has_one = array(
        'Thumb'=>'Image',
        'GalleryPage'=>'GalleryPage'
	);
    
    private static $many_many = array(
        'BlogTags' => 'BlogTag',
        'GalleryImages' => 'Image',
    );
    
    private static $many_many_extraFields = array(
        'GalleryImages' => array('SortOrder' => 'Int')
    );
    
    private static $belongs_many_many = array(
        'BlogPosts' => 'BlogPostObject',
        'Events' => 'EventObject'
    );
    
    static $summary_fields = array(
        'MyThumb'=>'Thumb',
        'Title' => 'Title',
        'Type'=>'Type',
        'Order'=>'Order'
    );
    
    public function SortedImages(){
        return $this->GalleryImages()->Sort('SortOrder');
    }
    
    public function populateDefaults(){
        parent::populateDefaults();
        $this->Date = date('Y-m-d');
    }
    
    public function Title(){
        return $this->Title.' Gallery';
    }
    
    public function getOGTitle(){
        return $this->Title.' Gallery';
    }

    public function MyThumb(){ 
	   return $this->Thumb()->SetWidth(160);
    }
    
    function getOGImage() {
        return $this->Thumb();
    }

    function getOGDescription(){
        return $this->SEODescription;
    }
    
    public function MetaTags($includeTitle = true) {
        $tags = "";
        // Insert non-OG metatags here as you normally would
        $this->extend('MetaTags', $tags);
        return $tags;
    }
    
    function canView($member = null) {
        return true;
    }
    
    function AbsoluteLink() {
        return Director::absoluteURL($this->Link());
    }
    
    public function Link(){
            //return $this->GalleryPage()->Link('show/'.$this->ID."/".$this->URLSegment);
            return $this->LinkGallery();
    }
    
    public function LinkGallery(){
            return $baseURL.'galleries/show/'.$this->ID.'/'.$this->URLSegment;
    }
    
    public function LinkingMode(){
        return Controller::curr()->getRequest()->param('ID') == $this->ID ? 'current' : 'link';
    }

    function onBeforeWrite () {
		parent::onBeforeWrite ();
		if($this->Title)
			$this->URLSegment = SiteTree::generateURLSegment($this->Title);
	}
    
    public function getCMSFields(){
        $fields = FieldList::create(TabSet::create('Root'));
        $fields->addFieldsToTab('Root.Main', array(
            TextField::create('Title'),
            TextField::create('URLSegment'),
            TextField::create('FolderName'),
            HTMLEditorField::create('Description'),
            TextareaField::create('SEODescription'),
            DateField::create('Date')->setConfig('dateformat', 'dd-MM-yyyy')->setConfig('showcalendar', true),
            NumericField::create('Order'),
            CheckboxField::create('RelativeActive','Show Relative Content'),
            TagField::create('BlogTags','Blog Tags',BlogTag::get(),$this->BlogTags())->setShouldLazyLoad(true)->setCanCreate(true)     // new tag DataObjects can be created
        ));
        $fields->addFieldToTab('Root.Main',$upload = new UploadField('Thumb'));
        $upload->SetFolderName('GalleryThumbs');
        
        $fields->addFieldToTab(
                                'Root.Upload',
                                $uploadField = new SortableUploadField('GalleryImages','Upload one or more images')
                              );
        $uploadField->setFolderName($this->URLSegment);
        $uploadField->setAllowedMaxFileNumber(32);
        
        $this->extend('updateCMSFields', $fields);
        return $fields;
    } 
    
}`

**Comment by Digitweaks** [comment]
Nevermind, i was working on 2 different project at a time and was trying the plugin on the website where i didn't even put the "sortablefile" folder... that's me working at 4-5am in automatic mode not realizing i forget the basics. Thanks for your time
