### ISSUE TITLE
SilverStripe 4

### ISSUE THREAD

**Issue by joeherbert** [bummzack/sortablefile#50]
This is a really useful module. Are you planning on making it compatible with SilverStripe 4?

**Comment by bummzack** [comment]
Yes. I'd have to wait for this bug to get resolved though: https://github.com/silverstripe/silverstripe-admin/issues/364

**Comment by sparkcom** [comment]
@bummzack https://github.com/silverstripe/silverstripe-admin/issues/364 is now closed. hope you have time to have a look soon. Best Regards,

**Comment by IrcDirk** [comment]
Do u have time to upgrade it to SS4?

**Comment by bummzack** [comment]
@IrcDirk Yeah soon, why? Do you want to do it?

**Comment by IrcDirk** [comment]
Im just starting with SilverStripe, so i dont have enough knowledge yet. 
But i find your extension very interesting and i would like to use it in my projects that are using SS4.
Thanks and keep up the good work.

**Comment by bummzack** [comment]
Ah ok. Thanks for your nice words. It's on my radar… I hope that I can upgrade the module in the coming weeks

**Comment by nglasl** [comment]
@bummzack, I noticed your active development on this in the past week. How far away do you think we are from a release? Great work so far :)

**Comment by bummzack** [comment]
@nglasl Haha, now I feel watched. It's pretty close. The minimum requirement will be 4.1, if this change makes it into 4.1, that is: https://github.com/silverstripe/silverstripe-asset-admin/pull/741

Stay tuned.

**Comment by bummzack** [comment]
Teaser for your viewing pleasure 😉 

![sorting preview](https://user-images.githubusercontent.com/1006185/36834528-77c5545c-1d33-11e8-981e-5bc763c6265a.gif)

**Comment by bummzack** [comment]
Alpha release is now available:

    composer require bummzack/sortablefile ^2@dev

Thanks to everybody for their patience!
