### ISSUE TITLE
Draggable area looks broken

### ISSUE THREAD

**Issue by danielschweiger** [bummzack/sortablefile#55]
![bildschirmfoto 2018-08-17 um 16 06 04](https://user-images.githubusercontent.com/2277612/44270335-86025180-a237-11e8-8906-508d5138ddc2.png)

If I remove the :: it looks good.

![bildschirmfoto 2018-08-17 um 16 07 42](https://user-images.githubusercontent.com/2277612/44270399-b8ac4a00-a237-11e8-9cff-49c033da923e.png)

**Comment by bummzack** [comment]
Thanks for reporting this… seems like something changed in the framework CSS I was relying on. Fixed in latest release: https://github.com/bummzack/sortablefile/releases/tag/2.1.2
