### ISSUE TITLE
Silverstripe 5 support

### ISSUE THREAD

**Issue by Sitetools** [bummzack/sortablefile#65]
Could you please let me know if or when you'll offer Silverstripe 5 support?
We use your addon on a few of our key projects and would like to continue using it.
Also do you have a timeline for when you'll support PHP 8.2.

CC @axllent

**Comment by dizzystuff** [comment]
+1 :)

**Comment by bummzack** [comment]
Can you try with the latest release (`2.2.0`) and report back if it works as expected?

**Comment by Sitetools** [comment]
Thank you for pushing that update, I have tested on Silverstripe 5 with both PHP 8.1 and PHP 8.2 and it works well for me.
